version: "1.0"
stages:
  - checkout
  - test
  - build
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    stage: checkout
    repo: "inspirasiprogrammer/Tugas-MVC-Golang2"
    revision: master
    git: github
  MyUnitTests:
    title: Unit test
    stage: test
    image: "golang:1.12"
    commands:
      - go test -v
  MyAppDockerImage:
    title: Building Docker Image
    type: build
    stage: build
    image_name: my-golang-image
    working_directory: ./
    tag: modules
    dockerfile: Dockerfile.mod
